<?php
return [
    'login_title' => 'Anmeldung',
    'login_description' => 'Bitte melden Sie sich an, um fortzufahren',
    'username' => 'Benutzername',
    'username_placeholder' => 'Benutzername',
    'password' => 'Passwort',
    'login' => 'Anmelden',
    'register' => 'Registrieren',
    'register_title' => 'Registrierung',
    'register_description' => 'Erstellen Sie ein neues Konto',
    'fullname' => 'Vollständiger Name',
    'fullname_placeholder' => 'Max Mustermann',
    'email' => 'E-Mail',
    'email_placeholder' => 'beispiel@domain.de',
    'no_account' => 'Noch kein Konto?',
    'have_account' => 'Bereits ein Konto vorhanden?',
    'back_to_home' => 'Zurück zur Startseite',
    'all_fields_required' => 'Alle Felder müssen ausgefüllt werden!',
    'invalid_credentials' => 'Ungültiger Benutzername oder Passwort.',
    'username_unavailable' => 'Dieser Benutzername ist bereits vergeben.',
    'email_unavailable' => 'Diese E-Mail-Adresse wird bereits verwendet.',
    'registration_error' => 'Bei der Registrierung ist ein Fehler aufgetreten.',
    'registration_success' => 'Registrierung erfolgreich! Sie können sich jetzt anmelden.',
];
