<?php
return [
    'bad_request_title' => 'Fehlerhafte Anfrage',
    'bad_request_message' => 'Der Server konnte deine Anfrage nicht verstehen.',
    'unauthorized_title' => 'Nicht autorisiert',
    'unauthorized_message' => 'Zum Zugriff ist eine Anmeldung erforderlich.',
    'forbidden_title' => 'Verboten',
    'forbidden_message' => 'Du hast keine Berechtigung, diese Seite anzusehen.',
    'not_found_title' => 'Nicht gefunden',
    'not_found_message' => 'Die gesuchte Seite wurde nicht gefunden.',
    'method_not_allowed_title' => 'Methode nicht erlaubt',
    'method_not_allowed_message' => 'Diese Aktion ist nicht erlaubt.',
    'request_timeout_title' => 'Zeitüberschreitung',
    'request_timeout_message' => 'Der Server hat nicht rechtzeitig eine Antwort erhalten.',
    'too_many_requests_title' => 'Zu viele Anfragen',
    'too_many_requests_message' => 'Du hast in kurzer Zeit zu viele Anfragen gesendet.',
    'internal_error_title' => 'Interner Serverfehler',
    'internal_error_message' => 'Auf dem Server ist ein Fehler aufgetreten. Bitte versuche es später erneut.',
    'not_implemented_title' => 'Nicht implementiert',
    'not_implemented_message' => 'Der Server unterstützt die angeforderte Funktion nicht.',
    'bad_gateway_title' => 'Fehlerhaftes Gateway',
    'bad_gateway_message' => 'Der Server hat eine ungültige Antwort vom Hintergrundsystem erhalten.',
    'service_unavailable_title' => 'Dienst nicht verfügbar',
    'service_unavailable_message' => 'Der Server ist aufgrund von Wartung oder Überlastung derzeit nicht verfügbar.',
    'gateway_timeout_title' => 'Gateway-Zeitüberschreitung',
    'gateway_timeout_message' => 'Der Server hat keine rechtzeitige Antwort vom Hintergrundsystem erhalten.',
    'error_title' => 'Fehler',
    'error_message' => 'Ein unerwarteter Fehler ist aufgetreten.'
];
