<?php
return [
    'bad_request_title' => 'Ungültige Anfrage',
    'bad_request_message' => 'Der Server konnte Ihre Anfrage nicht verstehen.',
    'unauthorized_title' => 'Nicht autorisiert',
    'unauthorized_message' => 'Anmeldung erforderlich, um auf diese Ressource zuzugreifen.',
    'forbidden_title' => 'Verboten',
    'forbidden_message' => 'Sie haben keine Berechtigung, diese Seite anzuzeigen.',
    'not_found_title' => 'Nicht gefunden',
    'not_found_message' => 'Die angeforderte Seite wurde nicht gefunden.',
    'method_not_allowed_title' => 'Methode nicht erlaubt',
    'method_not_allowed_message' => 'Dieser Vorgang ist nicht zulässig.',
    'request_timeout_title' => 'Zeitüberschreitung der Anforderung',
    'request_timeout_message' => 'Der Server hat keine rechtzeitige Antwort erhalten.',
    'too_many_requests_title' => 'Zu viele Anfragen',
    'too_many_requests_message' => 'Sie haben zu viele Anfragen in kurzer Zeit gesendet.',
    'internal_error_title' => 'Interner Serverfehler',
    'internal_error_message' => 'Auf dem Server ist ein Fehler aufgetreten. Bitte versuchen Sie es später noch einmal.',
    'not_implemented_title' => 'Nicht implementiert',
    'not_implemented_message' => 'Der Server unterstützt die angeforderte Funktion nicht.',
    'bad_gateway_title' => 'Bad Gateway',
    'bad_gateway_message' => 'Der Server hat eine ungültige Antwort vom Upstream-Server erhalten.',
    'service_unavailable_title' => 'Dienst nicht verfügbar',
    'service_unavailable_message' => 'Der Server ist derzeit wegen Wartungsarbeiten oder Überlastung nicht verfügbar.',
    'gateway_timeout_title' => 'Gateway-Zeitüberschreitung',
    'gateway_timeout_message' => 'Der Server hat keine rechtzeitige Antwort vom Upstream-Server erhalten.',
    'error_title' => 'Fehler',
    'error_message' => 'Ein unerwarteter Fehler ist aufgetreten.',
    'title' => 'Hoppla, ein Fehler ist aufgetreten.',
    'description' => 'Ein unbekannter Fehler ist aufgetreten.',
    'home_button' => 'Startseite',
    'back_button' => 'Zurück',
    'app_label' => 'Anwendung',
    'swiftphp_label' => 'SwiftPHP',
];
