<?php
return [
    'login_title' => 'Entrar',
    'login_description' => 'Faça login para continuar',
    'username' => 'Nome de usuário',
    'username_placeholder' => 'nome de usuário',
    'password' => 'Senha',
    'login' => 'Entrar',
    'register' => 'Cadastrar',
    'register_title' => 'Cadastro',
    'register_description' => 'Crie uma nova conta',
    'fullname' => 'Nome completo',
    'fullname_placeholder' => 'João Silva',
    'email' => 'E-mail',
    'email_placeholder' => 'exemplo@dominio.pt',
    'no_account' => 'Ainda não tem uma conta?',
    'have_account' => 'Já tem uma conta?',
    'back_to_home' => 'Voltar ao início',
    'all_fields_required' => 'Todos os campos são obrigatórios!',
    'invalid_credentials' => 'Nome de usuário ou senha inválidos.',
    'username_unavailable' => 'Este nome de usuário já está em uso.',
    'email_unavailable' => 'Este endereço de e-mail já está sendo utilizado.',
    'registration_error' => 'Ocorreu um erro durante o cadastro.',
    'registration_success' => 'Cadastro realizado com sucesso! Agora você pode entrar.',
];
