<?php
return [
    'bad_request_title' => 'Pedido inválido',
    'bad_request_message' => 'O servidor não conseguiu compreender o seu pedido.',
    'unauthorized_title' => 'Não autorizado',
    'unauthorized_message' => 'É necessário iniciar sessão para aceder a este recurso.',
    'forbidden_title' => 'Proibido',
    'forbidden_message' => 'Não tem permissão para visualizar esta página.',
    'not_found_title' => 'Não encontrado',
    'not_found_message' => 'A página solicitada não foi encontrada.',
    'method_not_allowed_title' => 'Método não permitido',
    'method_not_allowed_message' => 'Esta ação não é permitida.',
    'request_timeout_title' => 'Tempo de pedido excedido',
    'request_timeout_message' => 'O servidor não recebeu uma resposta atempada.',
    'too_many_requests_title' => 'Demasiados pedidos',
    'too_many_requests_message' => 'Enviou demasiados pedidos num curto período de tempo.',
    'internal_error_title' => 'Erro interno do servidor',
    'internal_error_message' => 'Ocorreu um erro no servidor. Tente novamente mais tarde.',
    'not_implemented_title' => 'Não implementado',
    'not_implemented_message' => 'O servidor não suporta a funcionalidade solicitada.',
    'bad_gateway_title' => 'Gateway inválido',
    'bad_gateway_message' => 'O servidor recebeu uma resposta inválida do sistema upstream.',
    'service_unavailable_title' => 'Serviço indisponível',
    'service_unavailable_message' => 'O servidor está atualmente indisponível devido a manutenção ou sobrecarga.',
    'gateway_timeout_title' => 'Tempo limite do gateway excedido',
    'gateway_timeout_message' => 'O servidor não recebeu uma resposta atempada do sistema upstream.',
    'error_title' => 'Erro',
    'error_message' => 'Ocorreu um erro inesperado.'
];
