<?php
return [
    'bad_request_title' => 'Requisição Inválida',
    'bad_request_message' => 'O servidor não entendeu a sua requisição.',
    'unauthorized_title' => 'Não autorizado',
    'unauthorized_message' => 'É necessário fazer login para acessar.',
    'forbidden_title' => 'Proibido',
    'forbidden_message' => 'Você não tem permissão para visualizar esta página.',
    'not_found_title' => 'Não encontrado',
    'not_found_message' => 'A página solicitada não foi encontrada.',
    'method_not_allowed_title' => 'Método não permitido',
    'method_not_allowed_message' => 'Esta operação não é permitida.',
    'request_timeout_title' => 'Tempo de requisição esgotado',
    'request_timeout_message' => 'O servidor não recebeu uma resposta a tempo.',
    'too_many_requests_title' => 'Excesso de requisições',
    'too_many_requests_message' => 'Você enviou muitas requisições em um curto período.',
    'internal_error_title' => 'Erro interno do servidor',
    'internal_error_message' => 'Algo deu errado no servidor. Por favor, tente novamente mais tarde.',
    'not_implemented_title' => 'Não implementado',
    'not_implemented_message' => 'O servidor não suporta a função solicitada.',
    'bad_gateway_title' => 'Bad Gateway',
    'bad_gateway_message' => 'O servidor recebeu uma resposta inválida do servidor de origem.',
    'service_unavailable_title' => 'Serviço indisponível',
    'service_unavailable_message' => 'O servidor está indisponível no momento devido a manutenção ou sobrecarga.',
    'gateway_timeout_title' => 'Tempo limite do gateway esgotado',
    'gateway_timeout_message' => 'O servidor não recebeu uma resposta a tempo do servidor de origem.',
    'error_title' => 'Erro',
    'error_message' => 'Ocorreu um erro inesperado.',
    'title' => 'Ops, ocorreu um erro.',
    'description' => 'Ocorreu um erro desconhecido.',
    'home_button' => 'Início',
    'back_button' => 'Voltar',
    'app_label' => 'Aplicação',
    'swiftphp_label' => 'SwiftPHP',
];
