<?php
return [
    'login_title' => 'Accesso',
    'login_description' => 'Accedi per continuare',
    'username' => 'Nome utente',
    'username_placeholder' => 'nome utente',
    'password' => 'Password',
    'login' => 'Accedi',
    'register' => 'Registrati',
    'register_title' => 'Registrazione',
    'register_description' => 'Crea un nuovo account',
    'fullname' => 'Nome completo',
    'fullname_placeholder' => 'Mario Rossi',
    'email' => 'E-mail',
    'email_placeholder' => 'esempio@dominio.it',
    'no_account' => 'Non hai ancora un account?',
    'have_account' => 'Hai già un account?',
    'back_to_home' => 'Torna alla home',
    'all_fields_required' => 'Tutti i campi sono obbligatori!',
    'invalid_credentials' => 'Nome utente o password non validi.',
    'username_unavailable' => 'Questo nome utente è già occupato.',
    'email_unavailable' => 'Questo indirizzo e-mail è già in uso.',
    'registration_error' => 'Si è verificato un errore durante la registrazione.',
    'registration_success' => 'Registrazione completata! Ora puoi accedere.',
];
