<?php
return [
    'bad_request_title' => 'Richiesta errata',
    'bad_request_message' => 'Il server non ha compreso la tua richiesta.',
    'unauthorized_title' => 'Non autorizzato',
    'unauthorized_message' => 'È necessario effettuare l\'accesso per continuare.',
    'forbidden_title' => 'Vietato',
    'forbidden_message' => 'Non hai i permessi necessari per visualizzare questa pagina.',
    'not_found_title' => 'Non trovato',
    'not_found_message' => 'La pagina richiesta non è stata trovata.',
    'method_not_allowed_title' => 'Metodo non consentito',
    'method_not_allowed_message' => 'Questa operazione non è consentita.',
    'request_timeout_title' => 'Tempo di richiesta scaduto',
    'request_timeout_message' => 'Il server non ha ricevuto una risposta tempestiva.',
    'too_many_requests_title' => 'Troppe richieste',
    'too_many_requests_message' => 'Hai inviato troppe richieste in un breve periodo di tempo.',
    'internal_error_title' => 'Errore interno del server',
    'internal_error_message' => 'Si è verificato un errore sul server. Riprova più tardi.',
    'not_implemented_title' => 'Non implementato',
    'not_implemented_message' => 'Il server non supporta la funzione richiesta.',
    'bad_gateway_title' => 'Gateway errato',
    'bad_gateway_message' => 'Il server ha ricevuto una risposta non valida dal server a monte.',
    'service_unavailable_title' => 'Servizio non disponibile',
    'service_unavailable_message' => 'Il server è temporaneamente non disponibile per manutenzione o sovraccarico.',
    'gateway_timeout_title' => 'Timeout del gateway',
    'gateway_timeout_message' => 'Il server non ha ricevuto una risposta tempestiva dal server a monte.',
    'error_title' => 'Errore',
    'error_message' => 'Si è verificato un errore imprevisto.',
    'title' => 'Ops, si è verificato un errore.',
    'description' => 'Si è verificato un errore sconosciuto.',
    'home_button' => 'Home',
    'back_button' => 'Indietro',
    'app_label' => 'Applicazione',
    'swiftphp_label' => 'SwiftPHP',
];
