<?php
return [
    'bad_request_title' => 'Richiesta non valida',
    'bad_request_message' => 'Il server non è riuscito a comprendere la richiesta.',
    'unauthorized_title' => 'Non autorizzato',
    'unauthorized_message' => 'È necessario effettuare l\'accesso per accedere a questa risorsa.',
    'forbidden_title' => 'Accesso negato',
    'forbidden_message' => 'Non hai i permessi per visualizzare questa pagina.',
    'not_found_title' => 'Non trovato',
    'not_found_message' => 'La pagina richiesta non è stata trovata.',
    'method_not_allowed_title' => 'Metodo non consentito',
    'method_not_allowed_message' => 'Questa azione non è consentita.',
    'request_timeout_title' => 'Timeout della richiesta',
    'request_timeout_message' => 'Il server non ha ricevuto una risposta tempestiva.',
    'too_many_requests_title' => 'Troppe richieste',
    'too_many_requests_message' => 'Hai inviato troppe richieste in un breve periodo di tempo.',
    'internal_error_title' => 'Errore interno del server',
    'internal_error_message' => 'Si è verificato un errore sul server. Riprova più tardi.',
    'not_implemented_title' => 'Non implementato',
    'not_implemented_message' => 'Il server non supporta la funzionalità richiesta.',
    'bad_gateway_title' => 'Gateway non valido',
    'bad_gateway_message' => 'Il server ha ricevuto una risposta non valida dal sistema upstream.',
    'service_unavailable_title' => 'Servizio non disponibile',
    'service_unavailable_message' => 'Il server è attualmente non disponibile a causa di manutenzione o sovraccarico.',
    'gateway_timeout_title' => 'Timeout del gateway',
    'gateway_timeout_message' => 'Il server non ha ricevuto una risposta tempestiva dal sistema upstream.',
    'error_title' => 'Errore',
    'error_message' => 'Si è verificato un errore imprevisto.'
];
