<?php
return [
    'login_title' => 'Belépés',
    'login_description' => 'Jelentkezzen be a folytatáshoz',
    'username' => 'Felhasználónév',
    'username_placeholder' => 'felhasználónév',
    'password' => 'Jelszó',
    'login' => 'Bejelentkezés',
    'register' => 'Regisztráció',
    'register_title' => 'Regisztráció',
    'register_description' => 'Hozzon létre egy felhasználót',
    'fullname' => 'Név',
    'fullname_placeholder' => 'Minta János',
    'email' => 'E-mail',
    'email_placeholder' => 'pelda@domain.hu',
    'no_account' => 'Nincs még fiókja?',
    'have_account' => 'Már van fiókja?',
    'back_to_home' => 'Vissza a főoldalra',
    'all_fields_required' => 'Minden mező kitöltése kötelező!',
    'invalid_credentials' => 'Érvénytelen felhasználónév vagy jelszó.',
    'username_unavailable' => 'Ez a felhasználónév már foglalt.',
    'email_unavailable' => 'Ez az e-mail cím már használatban van.',
    'registration_error' => 'Hiba történt a regisztráció során.',
    'registration_success' => 'Sikeres regisztráció! Most már bejelentkezhet.',
];
