<?php
return [
    'bad_request_title' => 'Hibás kérés',
    'bad_request_message' => 'A szerver nem értette a kérésedet.',
    'unauthorized_title' => 'Nem jogosult',
    'unauthorized_message' => 'Bejelentkezés szükséges a hozzáféréshez.',
    'forbidden_title' => 'Tiltott',
    'forbidden_message' => 'Nincs jogosultságod az oldal megtekintéséhez.',
    'not_found_title' => 'Nem található',
    'not_found_message' => 'A keresett oldal nem található.',
    'method_not_allowed_title' => 'Nem engedélyezett metódus',
    'method_not_allowed_message' => 'Ez a művelet nem engedélyezett.',
    'request_timeout_title' => 'Időtúllépés',
    'request_timeout_message' => 'A szerver nem kapott választ időben.',
    'too_many_requests_title' => 'Túl sok kérés',
    'too_many_requests_message' => 'Túl sok kérést küldtél rövid időn belül.',
    'internal_error_title' => 'Belső szerverhiba',
    'internal_error_message' => 'Valami hiba történt a szerveren. Kérjük próbáld újra később.',
    'not_implemented_title' => 'Nem megvalósított',
    'not_implemented_message' => 'A szerver nem támogatja a kért funkciót.',
    'bad_gateway_title' => 'Hibás átjáró',
    'bad_gateway_message' => 'A szerver érvénytelen választ kapott a háttérrendszertől.',
    'service_unavailable_title' => 'Szolgáltatás nem elérhető',
    'service_unavailable_message' => 'A szerver jelenleg nem elérhető karbantartás vagy túlterheltség miatt.',
    'gateway_timeout_title' => 'Átjáró időtúllépés',
    'gateway_timeout_message' => 'A szerver nem kapott választ időben a háttérrendszertől.',
    'error_title' => 'Hiba',
    'error_message' => 'Váratlan hiba történt.'
];
