<?php
return [
    'login_title' => 'Connexion',
    'login_description' => 'Veuillez vous connecter pour continuer',
    'username' => 'Nom d\'utilisateur',
    'username_placeholder' => 'nom d\'utilisateur',
    'password' => 'Mot de passe',
    'login' => 'Se connecter',
    'register' => 'S\'inscrire',
    'register_title' => 'Inscription',
    'register_description' => 'Créer un compte',
    'fullname' => 'Nom complet',
    'fullname_placeholder' => 'Jean Dupont',
    'email' => 'E-mail',
    'email_placeholder' => 'exemple@domaine.fr',
    'no_account' => 'Pas encore de compte ?',
    'have_account' => 'Vous avez déjà un compte ?',
    'back_to_home' => 'Retour à l\'accueil',
    'all_fields_required' => 'Tous les champs sont obligatoires !',
    'invalid_credentials' => 'Nom d\'utilisateur ou mot de passe invalide.',
    'username_unavailable' => 'Ce nom d\'utilisateur est déjà pris.',
    'email_unavailable' => 'Cette adresse e-mail est déjà utilisée.',
    'registration_error' => 'Une erreur est survenue lors de l\'inscription.',
    'registration_success' => 'Inscription réussie ! Vous pouvez maintenant vous connecter.',
];
