<?php
return [
    'bad_request_title' => 'Requête incorrecte',
    'bad_request_message' => 'Le serveur n’a pas pu comprendre votre requête.',
    'unauthorized_title' => 'Non autorisé',
    'unauthorized_message' => 'Connexion requise pour accéder à cette ressource.',
    'forbidden_title' => 'Interdit',
    'forbidden_message' => 'Vous n’avez pas la permission de consulter cette page.',
    'not_found_title' => 'Introuvable',
    'not_found_message' => 'La page demandée est introuvable.',
    'method_not_allowed_title' => 'Méthode non autorisée',
    'method_not_allowed_message' => 'Cette action n’est pas autorisée.',
    'request_timeout_title' => 'Délai dépassé',
    'request_timeout_message' => 'Le serveur n’a pas reçu de réponse à temps.',
    'too_many_requests_title' => 'Trop de requêtes',
    'too_many_requests_message' => 'Vous avez envoyé trop de requêtes en peu de temps.',
    'internal_error_title' => 'Erreur interne du serveur',
    'internal_error_message' => 'Une erreur est survenue sur le serveur. Veuillez réessayer plus tard.',
    'not_implemented_title' => 'Non implémenté',
    'not_implemented_message' => 'Le serveur ne prend pas en charge la fonctionnalité demandée.',
    'bad_gateway_title' => 'Mauvaise passerelle',
    'bad_gateway_message' => 'Le serveur a reçu une réponse invalide du système en arrière-plan.',
    'service_unavailable_title' => 'Service indisponible',
    'service_unavailable_message' => 'Le serveur est actuellement indisponible en raison de maintenance ou de surcharge.',
    'gateway_timeout_title' => 'Délai de passerelle dépassé',
    'gateway_timeout_message' => 'Le serveur n’a pas reçu de réponse à temps du système en arrière-plan.',
    'error_title' => 'Erreur',
    'error_message' => 'Une erreur inattendue est survenue.'
];
