<?php
return [
    'bad_request_title' => 'Requête incorrecte',
    'bad_request_message' => 'Le serveur n\'a pas compris votre requête.',
    'unauthorized_title' => 'Non autorisé',
    'unauthorized_message' => 'Connexion requise pour accéder à cette ressource.',
    'forbidden_title' => 'Interdit',
    'forbidden_message' => 'Vous n\'avez pas la permission d\'accéder à cette page.',
    'not_found_title' => 'Page non trouvée',
    'not_found_message' => 'La page demandée est introuvable.',
    'method_not_allowed_title' => 'Méthode non autorisée',
    'method_not_allowed_message' => 'Cette opération n\'est pas autorisée.',
    'request_timeout_title' => 'Délai d\'attente dépassé',
    'request_timeout_message' => 'Le serveur n\'a pas reçu de réponse à temps.',
    'too_many_requests_title' => 'Trop de requêtes',
    'too_many_requests_message' => 'Vous avez envoyé trop de requêtes en peu de temps.',
    'internal_error_title' => 'Erreur interne du serveur',
    'internal_error_message' => 'Une erreur est survenue sur le serveur. Veuillez réessayer plus tard.',
    'not_implemented_title' => 'Non implémenté',
    'not_implemented_message' => 'Le serveur ne prend pas en charge la fonction demandée.',
    'bad_gateway_title' => 'Mauvaise passerelle',
    'bad_gateway_message' => 'Le serveur a reçu une réponse invalide du serveur amont.',
    'service_unavailable_title' => 'Service indisponible',
    'service_unavailable_message' => 'Le serveur est actuellement indisponible pour maintenance ou surcharge.',
    'gateway_timeout_title' => 'Délai d\'attente de la passerelle dépassé',
    'gateway_timeout_message' => 'Le serveur n\'a pas reçu de réponse à temps du serveur amont.',
    'error_title' => 'Erreur',
    'error_message' => 'Une erreur inattendue est survenue.',
    'title' => 'Oups, une erreur est survenue.',
    'description' => 'Une erreur inconnue est survenue.',
    'home_button' => 'Accueil',
    'back_button' => 'Retour',
    'app_label' => 'Application',
    'swiftphp_label' => 'SwiftPHP',
];
