<?php
return [
    'login_title' => 'Iniciar sesión',
    'login_description' => 'Inicie sesión para continuar',
    'username' => 'Nombre de usuario',
    'username_placeholder' => 'nombre de usuario',
    'password' => 'Contraseña',
    'login' => 'Entrar',
    'register' => 'Registrarse',
    'register_title' => 'Registro',
    'register_description' => 'Cree una cuenta nueva',
    'fullname' => 'Nombre completo',
    'fullname_placeholder' => 'Juan Pérez',
    'email' => 'Correo electrónico',
    'email_placeholder' => 'ejemplo@dominio.es',
    'no_account' => '¿Aún no tienes cuenta?',
    'have_account' => '¿Ya tienes una cuenta?',
    'back_to_home' => 'Volver al inicio',
    'all_fields_required' => '¡Todos los campos son obligatorios!',
    'invalid_credentials' => 'Nombre de usuario o contraseña incorrectos.',
    'username_unavailable' => 'Este nombre de usuario ya está en uso.',
    'email_unavailable' => 'Este correo electrónico ya está registrado.',
    'registration_error' => 'Ocurrió un error durante el registro.',
    'registration_success' => '¡Registro completado con éxito! Ahora puedes iniciar sesión.',
];
