<?php
return [
    'bad_request_title' => 'Solicitud incorrecta',
    'bad_request_message' => 'El servidor no entendió su solicitud.',
    'unauthorized_title' => 'No autorizado',
    'unauthorized_message' => 'Se requiere iniciar sesión para acceder.',
    'forbidden_title' => 'Prohibido',
    'forbidden_message' => 'No tienes permiso para ver esta página.',
    'not_found_title' => 'No encontrado',
    'not_found_message' => 'No se pudo encontrar la página solicitada.',
    'method_not_allowed_title' => 'Método no permitido',
    'method_not_allowed_message' => 'Esta operación no está permitida.',
    'request_timeout_title' => 'Tiempo de espera agotado',
    'request_timeout_message' => 'El servidor no recibió una respuesta a tiempo.',
    'too_many_requests_title' => 'Demasiadas solicitudes',
    'too_many_requests_message' => 'Has enviado demasiadas solicitudes en poco tiempo.',
    'internal_error_title' => 'Error interno del servidor',
    'internal_error_message' => 'Algo salió mal en el servidor. Por favor, inténtelo de nuevo más tarde.',
    'not_implemented_title' => 'No implementado',
    'not_implemented_message' => 'El servidor no admite la función solicitada.',
    'bad_gateway_title' => 'Puerta de enlace incorrecta',
    'bad_gateway_message' => 'El servidor recibió una respuesta inválida del servidor de origen.',
    'service_unavailable_title' => 'Servicio no disponible',
    'service_unavailable_message' => 'El servidor no está disponible actualmente por mantenimiento o sobrecarga.',
    'gateway_timeout_title' => 'Tiempo de espera de la puerta de enlace agotado',
    'gateway_timeout_message' => 'El servidor no recibió una respuesta a tiempo del servidor de origen.',
    'error_title' => 'Error',
    'error_message' => 'Ocurrió un error inesperado.',
    'title' => '¡Uy! Ocurrió un error.',
    'description' => 'Ha ocurrido un error desconocido.',
    'home_button' => 'Inicio',
    'back_button' => 'Volver',
    'app_label' => 'Aplicación',
    'swiftphp_label' => 'SwiftPHP',
];
