<?php
return [
    'bad_request_title' => 'Solicitud incorrecta',
    'bad_request_message' => 'El servidor no pudo entender tu solicitud.',
    'unauthorized_title' => 'No autorizado',
    'unauthorized_message' => 'Se requiere iniciar sesión para acceder.',
    'forbidden_title' => 'Prohibido',
    'forbidden_message' => 'No tienes permiso para ver esta página.',
    'not_found_title' => 'No encontrado',
    'not_found_message' => 'La página solicitada no fue encontrada.',
    'method_not_allowed_title' => 'Método no permitido',
    'method_not_allowed_message' => 'Esta acción no está permitida.',
    'request_timeout_title' => 'Tiempo de espera agotado',
    'request_timeout_message' => 'El servidor no recibió una respuesta a tiempo.',
    'too_many_requests_title' => 'Demasiadas solicitudes',
    'too_many_requests_message' => 'Has enviado demasiadas solicitudes en poco tiempo.',
    'internal_error_title' => 'Error interno del servidor',
    'internal_error_message' => 'Ocurrió un error en el servidor. Por favor, inténtalo más tarde.',
    'not_implemented_title' => 'No implementado',
    'not_implemented_message' => 'El servidor no admite la función solicitada.',
    'bad_gateway_title' => 'Puerta de enlace incorrecta',
    'bad_gateway_message' => 'El servidor recibió una respuesta no válida del sistema de fondo.',
    'service_unavailable_title' => 'Servicio no disponible',
    'service_unavailable_message' => 'El servidor no está disponible actualmente debido a mantenimiento o sobrecarga.',
    'gateway_timeout_title' => 'Tiempo de espera de la puerta de enlace agotado',
    'gateway_timeout_message' => 'El servidor no recibió una respuesta a tiempo del sistema de fondo.',
    'error_title' => 'Error',
    'error_message' => 'Ocurrió un error inesperado.'
];
