<?php
return [
    'login_title' => 'Login',
    'login_description' => 'Please log in to continue',
    'username' => 'Username',
    'username_placeholder' => 'username',
    'password' => 'Password',
    'login' => 'Login',
    'register' => 'Register',
    'register_title' => 'Registration',
    'register_description' => 'Create a new account',
    'fullname' => 'Full Name',
    'fullname_placeholder' => 'John Doe',
    'email' => 'Email',
    'email_placeholder' => 'example@domain.com',
    'no_account' => 'Don\'t have an account yet?',
    'have_account' => 'Already have an account?',
    'back_to_home' => 'Back to home',
    'all_fields_required' => 'All fields are required!',
    'invalid_credentials' => 'Invalid username or password.',
    'username_unavailable' => 'This username is already taken.',
    'email_unavailable' => 'This email address is already in use.',
    'registration_error' => 'An error occurred during registration.',
    'registration_success' => 'Registration successful! You can now log in.',
];
