<?php
return [
    'bad_request_title' => 'Bad Request',
    'bad_request_message' => 'The server did not understand your request.',
    'unauthorized_title' => 'Unauthorized',
    'unauthorized_message' => 'Login is required to access this resource.',
    'forbidden_title' => 'Forbidden',
    'forbidden_message' => 'You do not have permission to view this page.',
    'not_found_title' => 'Not Found',
    'not_found_message' => 'The requested page could not be found.',
    'method_not_allowed_title' => 'Method Not Allowed',
    'method_not_allowed_message' => 'This operation is not allowed.',
    'request_timeout_title' => 'Request Timeout',
    'request_timeout_message' => 'The server did not receive a timely response.',
    'too_many_requests_title' => 'Too Many Requests',
    'too_many_requests_message' => 'You have sent too many requests in a short period.',
    'internal_error_title' => 'Internal Server Error',
    'internal_error_message' => 'Something went wrong on the server. Please try again later.',
    'not_implemented_title' => 'Not Implemented',
    'not_implemented_message' => 'The server does not support the requested feature.',
    'bad_gateway_title' => 'Bad Gateway',
    'bad_gateway_message' => 'The server received an invalid response from the upstream server.',
    'service_unavailable_title' => 'Service Unavailable',
    'service_unavailable_message' => 'The server is currently unavailable due to maintenance or overload.',
    'gateway_timeout_title' => 'Gateway Timeout',
    'gateway_timeout_message' => 'The server did not receive a timely response from the upstream server.',
    'error_title' => 'Error',
    'error_message' => 'An unexpected error occurred.',
    'title' => 'Oops, an error occurred.',
    'description' => 'An unknown error has occurred.',
    'home_button' => 'Home',
    'back_button' => 'Back',
    'app_label' => 'Application',
    'swiftphp_label' => 'SwiftPHP',
];
